config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only:[:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post
 def create
   @comment = @post.comments.create(comment_param)
   redirect_to post_path(@post)
 end

 def destroy
   @comment = @post.comments.find(params[:id])
   @comment.destroy
   redirect_to post_path(@post)
 end

 private
 def comment_param
   params.require(:comment).permit(:content)
 end
 def find_post
   @post = Post.find(params[:post_id])
 end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, except: [:index, :new, :create]
	def index
		@posts = Post.all
  end

  def show
		@comments = Comment.where(post_id: @post)
  end

  def new
		@post = Post.new
  end

  def create
		Post.create(post_param)
		redirect_to posts_path
  end

  def edit
  end

  def update
		@post.update(post_param)
		redirect_to posts_path
  end

  def destroy
		@post.destroy
		redirect_to posts_path
  end

	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_param
		params.require(:post).permit(:title, :content)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<% @comments.each do |c| %>
	<%= c.content %>
	<%= link_to "delete", post_comment_path(post_id: c.post_id, id: c.id), method: :DELETE %>
	<br>
<% end %>

<%= render "comments/form" %>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f|%>
  <%= f.text_field :title %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diana</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<h1>Posts#_form</h1>
<p>Find me in app/views/posts/_form.html.erb</p>

<%= form_for(@post) do |f|%>
  <%= f.text_field :title %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

<!-- _form 을 렌더링함 -->
<%= render "form" %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

<% @posts.each do |post| %>
  <%= post.title %>
  <%= link_to "show", post_path(post) %>
  <%= link_to "edit", edit_post_path(post) %>
  <%= link_to "delete", post_path(post), method: :DELETE %>
<% end %>

<%= link_to "new", new_post_path %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

<!-- _form 을 렌더링함 -->
<%= render "form" %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

<%= @post.title %><br>
<%= @post.content %><br>
<%= link_to "Back", posts_path %>

<h1>Comment</h1>

<%= render "comments/comment" %>